version: '3.1'

services:

    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 8888:3306
#        volumes:
#            - ./db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: zudoweb
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            - app-network

    adminer:
        image: adminer
        restart: always
        ports:
            - 8008:8080
        networks:
            - app-network

    web:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./web:/web
            - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        links:
            - php:php
    php:
#        image: php:5.6-fpm
        build: './docker/php'
        restart: always
        links:
            - db:db
        volumes:
            - ./web:/web
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
